const ADD_COORDINATE = '1';
const POP_COORDINATE = '2'
const DELETE_COORDINATE = '2';
const DELETE_ALL_COORDINATES = '0';
const JOINT_1_ADDRESS = '11';
const JOINT_4_ADDRESS = '41';
const JOINT_51_ADDRESS = '51';
const JOINT_52_ADDRESS = '52';
const HIGH_SPEED = '80';
const LOW_SPEED = '81';

module.exports = {
    ADD_COORDINATE,
    POP_COORDINATE,
    DELETE_COORDINATE,
    DELETE_ALL_COORDINATES,
    JOINT_1_ADDRESS,
    JOINT_4_ADDRESS,
    JOINT_51_ADDRESS,
    JOINT_52_ADDRESS,
    HIGH_SPEED,
    LOW_SPEED
}